<!DOCTYPE html>
<html ng-app="nmt" lang="en">
    <head>
        <title>Napier Management Training</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="initial-scale=1">
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/angularjs-toaster/0.4.4/toaster.css">
        <link href="/css/xeditable.css" rel="stylesheet" type="text/css"/>
        <link href="/css/loading-bar.css" rel="stylesheet" type="text/css"/>
        <link href="/css/custom.css" rel="stylesheet" type="text/css"/>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular-route.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular-cookies.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular-animate.min.js"></script>
        <script src="http://gregpike.net/demos/angular-local-storage/src/angular-local-storage.js"></script>
        <script src='http://cdnjs.cloudflare.com/ajax/libs/textAngular/1.2.2/textAngular-sanitize.min.js'></script>
        <script src='http://cdnjs.cloudflare.com/ajax/libs/textAngular/1.2.2/textAngular.min.js'></script>
        <script src="/js/xeditable.min.js"></script>
        <script src="/js/loading-bar.js" type="text/javascript"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.3/moment.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.11.0/ui-bootstrap-tpls.min.js"></script>
        <script src="/js/nmt.js" type="text/javascript"></script>
        <base href="/">
    </head>
    <body ng-controller="mainCtrl" ng-cloak>
        <a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>
        <header class="container-fluid">
            <a href="/home"><img src="/img/nmt.png" alt="" longdesc="Napier Management Training" id="logo"></a>
        </header>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li><a href="/home">Home</a></li>
                    <li><a href="/news">News</a></li>
                    <li><a href="/courses">Courses</a></li>
                    <li><a href="/venues">Venues</a></li>
                    <li><a href="/delegates">Register</a></li>
                </ul>
            </div>
        </nav>
        <div class="container">
            <div class="alert alert-danger">This web site is for demonstration purposes only and is part of an academic coursework for Managing Software Projects at School of Computing Edinburgh Napier University </div>
        </div>
        <?php echo $this->content; ?>
        <footer>
            <div class="container-fluid">
                <div class="col-xs-12 col-md-6 text-left">
                    <ul class="list-inline">
                        <li><a href="#"><img src="/img/facebook.png"></a></li>
                        <li><a href="#"><img src="/img/twitter.png"></a></li>
                        <li><a href="#"><img src="/img/google-plus.png"></a></li>
                        <li><a href="#"><img src="/img/linkedin.png"></a></li>
                    </ul>
                </div>
                <div class="col-xs-12 col-md-6 text-right">
                    <ul class="list-unstyled" id="footer-links">
                        <li><a href="/terms">Terms of service</a></li>
                        <li><a href="/admin/dashboard">Admin dashboard</a></li>
                    </ul>
                </div>
            </div>
        </footer>  
        <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/60204/toaster.js"></script>
        <toaster-container toaster-options="{'time-out': 3000,'spinner':false}"></toaster-container>
    </body>
</html>