<!DOCTYPE html>
<html ng-app="nmt">
    <head>
        <title>Napier Management Training</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="initial-scale=1">
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="css/custom.css" rel="stylesheet" type="text/css"/>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.0rc1/angular-route.min.js"></script>
        <script src="js/nmt.js" type="text/javascript"></script>
    </head>
    <body ng-controller="mainCtrl">
        <a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>
        <header class="container-fluid">
            <img class="img-responsive col-xs-12 col-md-4" src="img/napLogo.png" alt="Logo" id="logo"/>
            <h1 class="col-xs-12 col-md-offset-2 col-md-4">NMT</h1>
        </header>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li><a href="#news">News</a></li>
                    <li><a href="#courses">Courses</a></li>
                    <li><a href="#venues">Venues</a></li>
                    <li><a href="#delegates">Delegates</a></li>
                    <li><a href="#admin">Admin panel</a></li>
                </ul>
            </div>
        </nav>
        <div ng-view id="content">
            
        </div>
    </body>
</html>
